In [1]:
from pathlib import Path
import os
import sys

if Path.cwd().name == "notebooks":
    os.chdir("..")

ROOT = Path.cwd()

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

print("working from:", ROOT)

working from: e:\研究生\bootcamp\bootcamp_aixuan_liu\project

In [2]:
from src.ingestion import (
    load_daily_data,
    load_monthly_data
)

daily = load_daily_data()

monthly, beta = load_monthly_data()

display(daily.head())
display(monthly.head())
display(beta.head())

        date  close   day_r
0 2001-01-02  15.86  0.0332
1 2001-01-03  15.97  0.0069
2 2001-01-04  16.02  0.0031
3 2001-01-05  16.69  0.0418
4 2001-01-08  16.51 -0.0108

,date,Amount,MTTR,M_r,M_rf,PE,EPS,ROE,IPS
0,2001-01-19,2.935415e+08,15.6091,0.0365,0.00165,63.24,0.15,4.2458,0.95
1,2001-02-28,7.744882e+07,4.5339,-0.0880,0.00165,57.67,0.15,4.2458,0.95
2,2001-03-30,1.834463e+08,10.4055,0.0972,0.00165,63.28,0.25,6.2595,1.79
3,2001-04-30,1.927190e+08,10.5702,-0.0201,0.00165,77.93,0.25,6.2595,1.79
4,2001-05-31,3.678608e+08,18.6922,0.1776,0.00165,91.76,0.25,6.2595,1.79

        date    Beta
0 2001-01-19  0.9014
1 2001-02-28  0.9459
2 2001-03-30  0.9439
3 2001-04-30  0.9306
4 2001-05-31  0.9608

In [3]:
from src.cleaning import (
    clean_daily_data,
    clean_monthly_data
)

daily_clean = clean_daily_data(
    daily
)

monthly_clean = clean_monthly_data(
    monthly,
    beta
)

print(daily_clean.shape)
print(monthly_clean.shape)

(5417, 4)
(275, 10)

In [4]:
from src.features import build_features

factor_data = build_features(
    daily_clean,
    monthly_clean
)

factor_data.to_csv(
    "data/processed/factor_data.csv",
    index=False
)

factor_data.head()

,Amount,MTTR,M_r,M_rf,PE,EPS,ROE,IPS,yyyymm,Beta,...,PEL1,EPSL1,ROEL1,IPSL1,MTTRL1,BetaL1,M_volL1,M_liqL1,M_highL1,M_skewL1
0,1.834463e+08,10.4055,0.0972,0.00165,63.28,0.25,6.2595,1.79,200103,0.9439,...,57.67,0.15,4.2458,0.95,4.5339,0.9459,0.004541,-0.004844,0.909467,-1.214501
1,1.927190e+08,10.5702,-0.0201,0.00165,77.93,0.25,6.2595,1.79,200104,0.9306,...,63.28,0.25,6.2595,1.79,10.4055,0.9439,0.005040,0.005108,0.942012,0.649947
2,3.678608e+08,18.6922,0.1776,0.00165,91.76,0.25,6.2595,1.79,200105,0.9608,...,77.93,0.25,6.2595,1.79,10.5702,0.9306,0.004062,-0.001054,0.960947,-0.466222
3,2.549595e+08,12.5965,-0.0680,0.00165,85.32,0.25,6.2595,1.79,200106,1.5167,...,91.76,0.25,6.2595,1.79,18.6922,0.9608,0.005383,0.009005,1.131158,1.794370
4,1.019137e+08,5.4369,-0.1452,0.00165,98.13,0.25,6.2595,1.79,200107,1.4484,...,85.32,0.25,6.2595,1.79,12.5965,1.5167,0.008531,-0.003513,0.997823,-0.476625